# Site settings
title: Tek Sample Site

email: opensource at tektronix dot com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000"
twitter_username: nicknotbender
github_username:  nlynchjo

avatar: "/img/tekmonogram_tm.png"
navbar-img: "/img/doc_graphic5.png"
footer-img: "/img/doc_graphic5.png"
page-img: "/img/teklogo.png"


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
